# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main


variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'

stages:
 - stage: 'Build'
   displayname: 'Build, execution des tests et publication'
   pool:
    vmImage: 'ubuntu-latest'
   jobs:
    - job: 'Build'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
         command: 'restore'
         projects: '**/*.csproj'
         feedsToUse: 'select'
      displayName: 'Restauration des packages NuGet'

      - task: DotNetCoreCLI@2
        inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(buildConfiguration)'
       displayName: 'Génération des projets'

     - task: DotNetCoreCLI@2
       inputs:
        command: 'test'
        projects: '**/*Tests.csproj'
        arguments: '--configuration $(buildConfiguration)'
      displayName: 'Execution des  tests unitaires'

     - task: DotNetCoreCLI@2
       inputs:
         command: 'publish'
         publishWebProjects: true
         arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'mvcapp'
      publishLocation: 'Container'