# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main


variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'
  artifactName: 'mvcapp'

stages:
 - stage: 'Build'
   displayName: 'Build, execution des tests et publication'
   pool:
    vmImage: 'ubuntu-latest'
   jobs:
    - job: 'Build'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
         command: 'restore'
         projects: '**/*.csproj'
         feedsToUse: 'select'
        displayName: 'Restauration des packages NuGet'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'Génération des projets'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'Execution des  tests unitaires'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: $(artifactName)
          publishLocation: 'Container'

 - stage: 'DeployToDev'
   displayName: 'Déploiement en Dev'
   pool:
    vmImage: 'ubuntu-latest'
   dependsOn: 'Build'
   jobs:
     - template: templates/deploy-template.yml
       parameters:
         environment: 'Dev'
         artifactName: $(artifactName)
         serviceConnection: $(serviceConnection)
         webAppName: 'az-dev1-devops'

 - stage: 'DeployToTest'
   displayName: 'Déploiement en Test'
   pool:
    vmImage: 'ubuntu-latest'
   dependsOn: 'Build'
   jobs:
    - template: templates/deploy-template.yml
      parameters:
        environment: 'Test'
        artifactName: $(artifactName)
        serviceConnection: $(serviceConnection)
        webAppName: 'az-test-devops'
  
 - stage: 'DeployToProd'
   displayName: 'Déploiement en Prod'
   pool:
    vmImage: 'ubuntu-latest'
   dependsOn: 
      - 'DeployToDev'
      - 'DeployToTest'
   jobs:
     - template: templates/deploy-template.yml
       parameters:
        environment: 'Prod'
        artifactName: $(artifactName)
        serviceConnection: $(serviceConnection)
        webAppName: 'az-dev1-devops'