# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main


variables:
  buildConfiguration: 'Release'
  serviceConnection: 'sc-azure'

stages:
 - stage: 'Build'
   displayName: 'Build, execution des tests et publication'
   pool:
    vmImage: 'ubuntu-latest'
   jobs:
    - job: 'Build'
      steps:
      - task: DotNetCoreCLI@2
        inputs:
         command: 'restore'
         projects: '**/*.csproj'
         feedsToUse: 'select'
        displayName: 'Restauration des packages NuGet'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'build'
          projects: '**/*.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'Génération des projets'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'test'
          projects: '**/*Tests.csproj'
          arguments: '--configuration $(buildConfiguration)'
        displayName: 'Execution des  tests unitaires'

      - task: DotNetCoreCLI@2
        inputs:
          command: 'publish'
          publishWebProjects: true
          arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    
      - task: PublishBuildArtifacts@1
        inputs:
          PathtoPublish: '$(Build.ArtifactStagingDirectory)'
          ArtifactName: 'mvcapp'
          publishLocation: 'Container'

 - stage: 'DeployToDev'
   displayName: 'Déploiement en Dev'
   pool:
    vmImage: 'ubuntu-latest'
   jobs:
     - deployment: 'DeployToDev'
       environment: 'Dev'
       dependsOn: 'Build'
       strategy: 
         runOnce:
           deploy:
             steps: 
              - task: DownloadBuildArtifacts@1
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'mvcapp'
                  downloadPath: '$(System.ArtifactsDirectory)'
                displayName: 'Télécharger le package à déployer'

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'sc-azure'
                  appType: 'webApp'
                  WebAppName: 'az-dev1-devops'
                  packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
                displayName: 'Déploiement sur App Service'

 - stage: 'DeployToTest'
   displayName: 'Déploiement en Test'
   pool:
    vmImage: 'ubuntu-latest'
   jobs:
     - deployment: 'DeployToTest'
       environment: 'Test'
       dependsOn: 'Build'
       strategy: 
         runOnce:
           deploy:
             steps: 
              - task: DownloadBuildArtifacts@1
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'mvcapp'
                  downloadPath: '$(System.ArtifactsDirectory)'
                displayName: 'Télécharger le package à déployer'

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'sc-azure'
                  appType: 'webApp'
                  WebAppName: 'az-test-devops'
                  packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
                displayName: 'Déploiement sur App Service'
  
 - stage: 'DeployToProd'
   displayName: 'Déploiement en Prod'
   pool:
    vmImage: 'ubuntu-latest'
   jobs:
     - deployment: 'DeployToProd'
       environment: 'Prod'
       dependsOn: 'DeployToDev, DeployToTest'
       strategy: 
         runOnce:
           deploy:
             steps: 
              - task: DownloadBuildArtifacts@1
                inputs:
                  buildType: 'current'
                  downloadType: 'single'
                  artifactName: 'mvcapp'
                  downloadPath: '$(System.ArtifactsDirectory)'
                displayName: 'Télécharger le package à déployer'

              - task: AzureRmWebAppDeployment@4
                inputs:
                  ConnectionType: 'AzureRM'
                  azureSubscription: 'sc-azure'
                  appType: 'webApp'
                  WebAppName: 'az-prod-devops'
                  packageForLinux: '$(Build.ArtifactStagingDirectory)/**/*.zip'
                displayName: 'Déploiement sur App Service'