# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
   include:
     - main
  paths:
    include:
      - bicep

pool:
  vmImage: ubuntu-latest

variables:
  rg: 'rg-demo-iac-az'
  location: 'canadacentral'

steps:
- task: AzureCLI@2
  inputs:
    azureSubscription: 'sc-demo-devops'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      #az group create --name $(rg) --location $(location)
      #az deployment group create --resource-group $(rg) --template-file bicep/main.bicep --parameters appName=web-demo-iac-devops

      managedIdentityWebApp=$(az webapp identity show -n nugetpoo  -g rg-nuget --query principalId --output tsv)
      echo "Managed identity : $managedIdentityWebApp"

      az ad group member add --group myAzureSQLDBGroup --member-id $managedIdentityWebApp

  displayName: 'Création ressources Azure'
