# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

variables:
   artifactName: 'drop'
   serviceConnection: 'sc-demo-devops'

stages:
- stage: 'Build'
  displayName: 'Génération, exécution des test et publication'
  jobs:
  - template: templates/build-template.yml
    parameters:
      buildConfiguration: 'Release'
      artifactName: '$(artifactName)'
  
- stage: 'DeployToDev'
  displayName: 'Déploiment en dev'
  dependsOn: 'Build'
  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Dev'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      webAppName: 'webapp-demo-devops'

- stage: 'DeployToProd'
  displayName: 'Déploiment en prod'
  dependsOn: 'DeployToDev'
  jobs:
  - template: templates/deploy-template.yml
    parameters:
      environment: 'Prod'
      artifactName: '$(artifactName)'
      serviceConnection: '$(serviceConnection)'
      webAppName: 'webapp-demo-devops-prod'
